ERROR:root:An error occurred in login: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
ERROR:server:Exception on /api/auth/command/login [POST]
Traceback (most recent call last):
  File "d:\QUEE\QueezFlask\queez-flask-api\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\QUEE\QueezFlask\queez-flask-api\venv\Lib\site-packages\flask\app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\QUEE\QueezFlask\queez-flask-api\venv\Lib\site-packages\flask\app.py", line 1506, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "d:\QUEE\QueezFlask\queez-flask-api\venv\Lib\site-packages\flask\app.py", line 1837, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a bool.
INFO:werkzeug:127.0.0.1 - - [15/Nov/2023 10:03:59] "[35m[1mPOST /api/auth/command/login HTTP/1.1[0m" 500 -
ERROR:root:An error occurred in login: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
ERROR:server:Exception on /api/auth/command/login [POST]
Traceback (most recent call last):
  File "d:\QUEE\QueezFlask\queez-flask-api\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\QUEE\QueezFlask\queez-flask-api\venv\Lib\site-packages\flask\app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\QUEE\QueezFlask\queez-flask-api\venv\Lib\site-packages\flask\app.py", line 1506, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "d:\QUEE\QueezFlask\queez-flask-api\venv\Lib\site-packages\flask\app.py", line 1837, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, list, tuple with headers or status, Response instance, or WSGI callable, but it was a bool.
INFO:werkzeug:127.0.0.1 - - [15/Nov/2023 10:04:17] "[35m[1mPOST /api/auth/command/login HTTP/1.1[0m" 500 -
ERROR:root:An error occurred in get_query_by_code: (mysql.connector.errors.ProgrammingError) 1146 (42S02): Table 'queez.sys_query_string' doesn't exist
[SQL: SELECT sql_string,display_field,query_filter,filter_para FROM sys_query_string WHERE query_code = %(query_code)s ]
[parameters: {'query_code': 'get_user_by_username'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
ERROR:root:An error occurred in fetch_run_sql_select_query_string: 'bool' object has no attribute 'sql_string'
ERROR:root:An error occurred in authenticate: No user found with this username
INFO:werkzeug:127.0.0.1 - - [15/Nov/2023 10:05:25] "POST /api/auth/command/login HTTP/1.1" 200 -
ERROR:root:An error occurred in get_query_by_code: (mysql.connector.errors.ProgrammingError) 1146 (42S02): Table 'queez.sys_query_string' doesn't exist
[SQL: SELECT sql_string,display_field,query_filter,filter_para FROM sys_query_string WHERE query_code = %(query_code)s ]
[parameters: {'query_code': 'get_user_by_username'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
ERROR:root:An error occurred in fetch_run_sql_select_query_string: 'bool' object has no attribute 'sql_string'
ERROR:root:An error occurred in authenticate: No user found with this username
INFO:werkzeug:127.0.0.1 - - [15/Nov/2023 10:06:28] "POST /api/auth/command/login HTTP/1.1" 200 -
ERROR:root:An error occurred in get_query_by_code: (mysql.connector.errors.ProgrammingError) 1146 (42S02): Table 'queez.sys_query_string' doesn't exist
[SQL: SELECT sql_string,display_field,query_filter,filter_para FROM sys_query_string WHERE query_code = %(query_code)s ]
[parameters: {'query_code': 'get_user_by_username'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
ERROR:root:An error occurred in fetch_run_sql_select_query_string: 'bool' object has no attribute 'sql_string'
ERROR:root:An error occurred in authenticate: No user found with this username
INFO:werkzeug:127.0.0.1 - - [15/Nov/2023 10:07:45] "POST /api/auth/command/login HTTP/1.1" 200 -
ERROR:root:An error occurred in get_query_by_code: (mysql.connector.errors.ProgrammingError) 1146 (42S02): Table 'queez.sys_query_string' doesn't exist
[SQL: SELECT sql_string,display_field,query_filter,filter_para FROM sys_query_string WHERE query_code = %(query_code)s ]
[parameters: {'query_code': 'get_user_by_username'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
ERROR:root:An error occurred in fetch_run_sql_select_query_string: 'bool' object has no attribute 'sql_string'
ERROR:root:An error occurred in authenticate: No user found with this username
INFO:werkzeug:127.0.0.1 - - [15/Nov/2023 10:28:46] "POST /api/auth/command/login HTTP/1.1" 200 -
